# Generated by Django 5.0.3 on 2024-04-21 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.oblast')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=31, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+998([- ])?(90|91|93|94|95|98|99|33|97|71|88|)([- ])?(\\d{3})([- ])?(\\d{2})([- ])?(\\d{2})$')])),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='client')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_id', models.CharField(blank=True, max_length=5, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.rayon')),
            ],
        ),
    ]
