# Generated by Django 5.0.3 on 2024-04-22 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=31, validators=[django.core.validators.RegexValidator(message='Invalid phone number', regex='^\\+998([- ])?(90|91|93|94|95|98|99|33|97|71|88|)([- ])?(\\d{3})([- ])?(\\d{2})([- ])?(\\d{2})$')]),
        ),
    ]
